// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model;

#nullable disable

namespace Model.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250513001229_initial8")]
    partial class initial8
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.DocumentosUsuario", b =>
                {
                    b.Property<int>("IdDocumentoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocumentoUsuario"));

                    b.Property<int>("IdTipoDocumento")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Licencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoDocumentoIdTipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("TipoVehiculo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("Verificado")
                        .HasColumnType("bit");

                    b.HasKey("IdDocumentoUsuario");

                    b.HasIndex("TipoDocumentoIdTipoDocumento");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("DocumentosUsuario");
                });

            modelBuilder.Entity("Model.Encomiendas", b =>
                {
                    b.Property<int>("IdEncomienda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEncomienda"));

                    b.Property<string>("Destinatario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensiones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdRutaReserva")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoEncomienda")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEncomienda");

                    b.HasIndex("IdRutaReserva");

                    b.HasIndex("IdTipoEncomienda");

                    b.ToTable("Encomiendas");
                });

            modelBuilder.Entity("Model.EstadosReserva", b =>
                {
                    b.Property<int>("IdEstadoReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoReserva"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEstadoReserva");

                    b.ToTable("EstadosReserva");
                });

            modelBuilder.Entity("Model.EstadosRuta", b =>
                {
                    b.Property<int>("IdEstadoRuta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoRuta"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEstadoRuta");

                    b.ToTable("EstadosRuta");
                });

            modelBuilder.Entity("Model.RutasConductor", b =>
                {
                    b.Property<int>("IdRutaConductor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRutaConductor"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdEstadoRuta")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdRutaConductor");

                    b.HasIndex("IdEstadoRuta");

                    b.HasIndex("IdUsuario");

                    b.ToTable("RutasConductor");
                });

            modelBuilder.Entity("Model.RutasReserva", b =>
                {
                    b.Property<int>("IdRutaReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRutaReserva"));

                    b.Property<int>("CantidadPasajeros")
                        .HasColumnType("int");

                    b.Property<string>("DireccionDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionOrigen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstadoReserva")
                        .HasColumnType("int");

                    b.Property<int>("IdRutaConductor")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoReserva")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdRutaReserva");

                    b.HasIndex("IdEstadoReserva");

                    b.HasIndex("IdRutaConductor");

                    b.HasIndex("IdTipoReserva");

                    b.HasIndex("IdUsuario");

                    b.ToTable("RutasReserva");
                });

            modelBuilder.Entity("Model.TiposDocumento", b =>
                {
                    b.Property<int>("IdTipoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoDocumento"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoDocumento");

                    b.ToTable("TiposDocumento");
                });

            modelBuilder.Entity("Model.TiposEncomienda", b =>
                {
                    b.Property<int>("IdTipoEncomienda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoEncomienda"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoEncomienda");

                    b.ToTable("TiposEncomienda");
                });

            modelBuilder.Entity("Model.TiposReserva", b =>
                {
                    b.Property<int>("IdTipoReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoReserva"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoReserva");

                    b.ToTable("TiposReserva");
                });

            modelBuilder.Entity("Model.TiposUsuario", b =>
                {
                    b.Property<int>("IdTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoUsuario"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoUsuario");

                    b.ToTable("TiposUsuario");
                });

            modelBuilder.Entity("Model.Ubicaciones", b =>
                {
                    b.Property<int>("IdUbicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUbicacion"));

                    b.Property<string>("Latitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUbicacion");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("Model.UbicacionesRuta", b =>
                {
                    b.Property<int>("IdUbicacionRuta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUbicacionRuta"));

                    b.Property<int?>("IdRutaConductor")
                        .HasColumnType("int");

                    b.Property<int>("IdUbicacion")
                        .HasColumnType("int");

                    b.HasKey("IdUbicacionRuta");

                    b.HasIndex("IdRutaConductor");

                    b.HasIndex("IdUbicacion");

                    b.ToTable("UbicacionesRuta");
                });

            modelBuilder.Entity("Model.Usuarios", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCelular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroIdentificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImagen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdTipoUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Model.DocumentosUsuario", b =>
                {
                    b.HasOne("Model.TiposDocumento", "TipoDocumento")
                        .WithMany("DocumentosUsuario")
                        .HasForeignKey("TipoDocumentoIdTipoDocumento");

                    b.HasOne("Model.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("TipoDocumento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Model.Encomiendas", b =>
                {
                    b.HasOne("Model.RutasReserva", "RutasReserva")
                        .WithMany("Encomiendas")
                        .HasForeignKey("IdRutaReserva");

                    b.HasOne("Model.TiposEncomienda", "TipoEncomienda")
                        .WithMany("Encomiendas")
                        .HasForeignKey("IdTipoEncomienda")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RutasReserva");

                    b.Navigation("TipoEncomienda");
                });

            modelBuilder.Entity("Model.RutasConductor", b =>
                {
                    b.HasOne("Model.EstadosRuta", "EstadoRuta")
                        .WithMany("RutasConductor")
                        .HasForeignKey("IdEstadoRuta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario");

                    b.Navigation("EstadoRuta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Model.RutasReserva", b =>
                {
                    b.HasOne("Model.EstadosReserva", "EstadoReserva")
                        .WithMany("RutasReserva")
                        .HasForeignKey("IdEstadoReserva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.RutasConductor", "RutaConductor")
                        .WithMany("RutasReserva")
                        .HasForeignKey("IdRutaConductor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.TiposReserva", "TipoReserva")
                        .WithMany("RutasReserva")
                        .HasForeignKey("IdTipoReserva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Usuarios", "Usuario")
                        .WithMany("RutasReserva")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoReserva");

                    b.Navigation("RutaConductor");

                    b.Navigation("TipoReserva");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Model.UbicacionesRuta", b =>
                {
                    b.HasOne("Model.RutasConductor", "RutaConductor")
                        .WithMany("UbicacionesRuta")
                        .HasForeignKey("IdRutaConductor");

                    b.HasOne("Model.Ubicaciones", "Ubicacion")
                        .WithMany("UbicacionesRuta")
                        .HasForeignKey("IdUbicacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RutaConductor");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("Model.Usuarios", b =>
                {
                    b.HasOne("Model.TiposUsuario", "TipoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdTipoUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("Model.EstadosReserva", b =>
                {
                    b.Navigation("RutasReserva");
                });

            modelBuilder.Entity("Model.EstadosRuta", b =>
                {
                    b.Navigation("RutasConductor");
                });

            modelBuilder.Entity("Model.RutasConductor", b =>
                {
                    b.Navigation("RutasReserva");

                    b.Navigation("UbicacionesRuta");
                });

            modelBuilder.Entity("Model.RutasReserva", b =>
                {
                    b.Navigation("Encomiendas");
                });

            modelBuilder.Entity("Model.TiposDocumento", b =>
                {
                    b.Navigation("DocumentosUsuario");
                });

            modelBuilder.Entity("Model.TiposEncomienda", b =>
                {
                    b.Navigation("Encomiendas");
                });

            modelBuilder.Entity("Model.TiposReserva", b =>
                {
                    b.Navigation("RutasReserva");
                });

            modelBuilder.Entity("Model.TiposUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Model.Ubicaciones", b =>
                {
                    b.Navigation("UbicacionesRuta");
                });

            modelBuilder.Entity("Model.Usuarios", b =>
                {
                    b.Navigation("RutasReserva");
                });
#pragma warning restore 612, 618
        }
    }
}
